
package SoapInterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapServiceImpService", targetNamespace = "http://tk1ex2/", wsdlLocation = "http://localhost:8090/soapservices?wsdl")
public class SoapServiceImpService
    extends Service
{

    private final static URL SOAPSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICEIMPSERVICE_EXCEPTION;
    private final static QName SOAPSERVICEIMPSERVICE_QNAME = new QName("http://tk1ex2/", "SoapServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/soapservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICEIMPSERVICE_WSDL_LOCATION = url;
        SOAPSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public SoapServiceImpService() {
        super(__getWsdlLocation(), SOAPSERVICEIMPSERVICE_QNAME);
    }

    public SoapServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICEIMPSERVICE_QNAME, features);
    }

    public SoapServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICEIMPSERVICE_QNAME);
    }

    public SoapServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICEIMPSERVICE_QNAME, features);
    }

    public SoapServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "SoapServiceImpPort")
    public SoapService getSoapServiceImpPort() {
        return super.getPort(new QName("http://tk1ex2/", "SoapServiceImpPort"), SoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "SoapServiceImpPort")
    public SoapService getSoapServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tk1ex2/", "SoapServiceImpPort"), SoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw SOAPSERVICEIMPSERVICE_EXCEPTION;
        }
        return SOAPSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
